# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: "Removing and adding correct version of gcc"
          command: "sudo apt-get remove gcc g++ && sudo apt-get install gcc-4.9 g++-4.9"
      - run:
          name: "Install Dependencies"
          command: "bash install_dependencies.sh"
      - run:
          name: "Install LifeSim"
          command: "chmod +x -R * && ./install_pin.sh && make -j 4"
workflows:
  version: 2
  build:
    jobs:
      - build
